### PR TITLE
Use namespaced loaders rather than method with global scope

### PR DESCRIPTION
**Pull request by pyrmont**
Rouge currently uses two global methods, `#load_relative` and `#lexer_dir`, defined in `lib/rouge.rb` to load the various files that constitute Rouge. Rather than pollute the global namespace, it would be preferable if the loading methods were within the `Rouge` module.

This PR adds two top-level methods to `Rouge`'s singleton class: `#load_file` and `#load_lexers`. It is a fork of, and builds on the work of @ashmaroli in, #1430.

### CODE REVIEW

**Comment by ashmaroli** [comment]
Thank you for taking on this @pyrmont 
I know that it is going to be insignificant but as an FYI, it is always better (*memory-allocation wise*) to provide as little parameters as possible without affecting readability to `File.join` especially since `/` is the default separator on all platforms including Windows.
i.e.:
`File.join(variable, 'foo', 'bar', 'lipsum')` will allocate more strings than
`File.join(variable, 'foo/bar/lipsum')`

**Comment by pyrmont** [comment]
@ashmaroli Ta! Do you think it needs anything else?

**Comment by ashmaroli** [comment]
Technically, `# @api private` has no significance but to serve as a note to the adventurous..
How about moving all the `load_*` calls under the `Rouge` singleton class. That way, the `load_*` methods could be truly marked as `private` ..

```ruby
module Rouge
  class << self
    def reload!
      ...
    end

    private

    def load_file(path)
      ...
    end

    load_file 'version'
  end
end
```

In theory, it should work seamlessly with Rouge's existing workflow. However, I've not tested it and therefore if you feel it is unnecessary or if it won't work in practice, the pull request as of this comment looks good to be merged.

**Comment by pyrmont** [comment]
@ashmaroli We can't actually make the methods private because they're called from outside Rouge (_technically_ you could still call them using `Object#send` but obviously that's not something we want to be doing). While marking the methods as `@api private` doesn't prevent anyone else from using them, I think it's a decent compromise.

I did make one more change, though. Given that the methods are not intended to be part of a public API, I've moved them below the `#reload!` and `#highlight` methods so the intent is a little clearer structurally.

Thanks for the feedback and the initial PR!

**Comment by ashmaroli** [comment]
> because they're called from outside Rouge

Yeah that's why I suggested moving the calls inside the Rouge singleton class in my comment.
Either ways, let us run with the current implementation for some time.
Thanks for handling this @pyrmont

**Comment by pyrmont** [comment]
Ah, I see what you meant. Sorry about that. My misunderstanding. Agreed to see how this goes for now :)

**Pull request merged**
