### PR TITLE
Fix character escaping in Perl lexer

### LINKED ISSUE #1163: When inside single quotes, Perl tokenizes \ as an error
Problem:

image

I tried adding the following rule as the 3rd rule of states `:sq` and `:dq` and it fixes it, but of course IDK if this is the right solution.

```ruby
      state :sq do
        rule /\\[']/, Str::Escape
        rule /[^\\']+/, Str::Single
+        rule /\\/, Str::Single
        rule /'/, Punctuation, :pop!
      end

      state :dq do
        mixin :string_intp
        rule /\\[\\tnr"]/, Str::Escape
        rule /[^\\"]+?/, Str::Double
+        rule /\\/, Str::Single
        rule /"/, Punctuation, :pop!
      end
```

image

### PR DESCRIPTION
**Pull request by pyrmont**
In single-quoted strings, the Perl lexer currently tokenises `\` as an error if it is followed by any character other than a `'`. This is a bug. Perl accepts the use of `\` in single-quoted strings.

In the course of fixing this, errors in the handling of character escaping in double-quoted strings was also addressed. In that case, `$` and `@` are also valid characters to escape. The use of `\` can still produce `Error` tokens in double-quoted strings if followed by another character.

This fixes #1163.

### CODE REVIEW

**Comment by pyrmont** [comment]
@miparnisari I am very much out of my depth with Perl but tried to experiment with how it handles the `\` in double-quoted strings by running `perl -de1` at the command line and playing around a bit with `print`. If I run `print "foo\bar", I get the output `"fooar" which doesn't really make sense to me at all but makes me think that `\` should be lexed as an error unless it's followed by a valid character to escape. What do you think?

**Comment by jeremychan** [comment]
Do you mean you get "foar"? \b is a backspace http://www.java2s.com/Code/Perl/String/BackslashEscapesinPerl.htm

**Comment by pyrmont** [comment]
@jeremychan Sorry, right you are. Thanks for the correction! I'll have a closer look at that list and see if I need to make any more changes :)

**Comment by pyrmont** [comment]
It seems surprisingly difficult to determine the valid escape sequences in a Perl string. Using a combination of the lists from [the Perl regular expression documentation](https://perldoc.perl.org/perlrebackslash.html) and [the Encode::Escape CPAN module](https://metacpan.org/pod/Encode::Escape), I've added more robust escaping support.

**Pull request merged**
