### PR TITLE
Rust: Fix integer literals' delimiters

### PR DESCRIPTION
**Pull request by rhysd**
I noticed `_` is not lexed as delimiter in integer literals. This PR fixes the point. Additionally, `-` was considered as delimiter in `0x` literal, but it's not correct. I also fixed the point.

example:

```rust
123_456_789
0x123_456_789_abc
```

### CODE REVIEW

**Comment by pyrmont** [comment]
@rhysd I'm really sorry this has been outstanding for so long. It looks good but could you add some examples to the Rust visual sample for future reference? The file is in `spec/visual/samples/rust`.

**Comment by rhysd** [comment]
I added it at 0d699b0. Please check the sample is sufficient in terms of reference.

> I'm really sorry this has been outstanding for so long.

Please never mind. Thank you for maintaining awesome project.

**Comment by pyrmont** [comment]
Thanks for updating it so quickly! Just waiting for the Travis CI build to complete and then I'll merge :)

**Comment by pyrmont** [comment]
Thanks again for the contribution! :)

**Pull request merged**
