### PR TITLE
Add FreeFEM lexer (inherited from C++)

### PR DESCRIPTION
**Pull request by sgarnotel**
Lexer for [FreeFEM](https://freefem.org/), following the recommandations of [PR #1020](https://github.com/rouge-ruby/rouge/pull/1020)

### CODE REVIEW

**Comment by pyrmont** [comment]
@sgarnotel Sorry, this took a lot longer to get to than I originally intended! I've made some minor (mostly stylistic changes). Let me know what you think!

**Comment by sgarnotel** [comment]
@pyrmont It is ok for me.
On the other hand, in the demo, I wanted to test the `'` operator, but it is not such important.
Thanks

**Comment by pyrmont** [comment]
@sgarnotel The demo is really just to make sure that the lexer loads. It's not really intended to be used for testing of the lexing of particular constructs.

If you want to do that, you can either add the construct to your visual spec and then check it visually or you can add it to the test file for the particular lexer. You can see an example of how that would work in [the recent PR](https://github.com/rouge-ruby/rouge/blob/e2b6fd920abebe80974efb3cc88c6c90da47b251/spec/lexers/console_spec.rb#L19-L22) for the Console lexer.

**Comment by sgarnotel** [comment]
@pyrmont Ok, so all is ok for me

**Comment by pyrmont** [comment]
Cool. I'll merge this now and it'll be in the next release of Rouge coming 14 January.

**Pull request merged**
