### PR TITLE
Enable libsonnet suffix in jsonnet language

### PR DESCRIPTION
**Pull request by tvi**

### CODE REVIEW

**Comment by pyrmont** [comment]
@tvi I'm sorry it's taken so long to get back to you on this.

Could you please add a test to the jsonnet spec checking this? You can see the existing test here:

https://github.com/rouge-ruby/rouge/blob/c00d6d1f8f86e0bae61c80fa80f73bbfeb0399bd/spec/lexers/jsonnet_spec.rb#L10-L12

Will be good to merge after that.

**Comment by tvi** [comment]
@pyrmont done

**Comment by pyrmont** [comment]
@tvi Thanks for responding so quickly!

**Comment by pyrmont** [comment]
Thanks for the PR! It's great to make Rouge a little more capable :)

**Pull request merged**
