### PR TITLE
resolves #264 add line highlighting option

### LINKED ISSUE #264: Line highlighting like pygments hl_lines
I'm looking for the ability to highlight lines, either to call attention to specific code in a tutorial, or note added code in a running example.

Pygments offers the hl_lines option, such as hl_lines="3 4 5". This adds span element w css class of "hll" to the generated html for that line.

Is this something that has been talked about or planned?

### PR DESCRIPTION
**Pull request by mojavelinux**
- add line highlighting option to HTMLLinewise formatter
- add dedicated formatter to add line highlighting (only marks highlighted lines)

### CODE REVIEW

**Comment by pyrmont** [comment]
Sorry about the delay, @mojavelinux. I got a bit side-tracked with various things.

@jneen has expressed in the past a reluctance to add further formatters to Rouge. @jneen, what do you think about this PR?

**Comment by mojavelinux** [comment]
Thanks. As I said in #264, "If you think the additional formatter is unnecessary, I can remove it."

**Comment by jneen** [comment]
This seems okay to me, mostly because it's its own class. My major reluctance is to adding options to existing formatters.

**Comment by mojavelinux** [comment]
Thanks for reviewing. I've gone ahead and removed the change that introduced the additional options to the existing formatter. Let me know if you need me to make any other changes.

**Comment by nektro** [comment]
Any updates on this / is there anything blocking?

**Comment by jneen** [comment]
Looks good to me. It's using a `\n` for a newline, which seems to indicate it needs to be in a `<pre>` block of some kind, rather than using divs or otherwise. But I think it's okay. There's so many ways to format in HTML that I consider the builtin HTML formatters here to be more like... documentation. Or just the very basic use cases. I'm +1 to merge.

**Review by pyrmont — APPROVED** [review]

**Comment by jneen** [comment]
and merged! thanks all <3

**Pull request merged**
