### PR TITLE
Add a Varnish lexer

### PR DESCRIPTION
**Pull request by julp**
Proposal for a Varnish (VCL) lexer

### CODE REVIEW

**Comment by gfx** [comment]
I've looked at it based on the master (v2.1.0), and it works well.

LGTM.

cc: @jneen

**Comment by gfx** [comment]
There are examples available from:

* https://varnish-cache.org/docs/trunk/users-guide/vcl-examples.html

**Comment by blckct** [comment]
I could use that. Is there something that needs to be done to get this accepted?

**Comment by gfx** [comment]
Sorry to be late, but now I'll merge this PR.

@pyrmont HI! I'd like to merge this PR because I am now interested in Varnish.

**Comment by gfx** [comment]
Note: I'll fix some warnings after merging it.

**Pull request merged**
