### PR TITLE
Add support for first-class expressions to Terraform lexer

### LINKED ISSUE #1301: Support first-class expressions for Terraform 0.12
**Name of the lexer**
Terraform

**Online example**
Sorry, I couldn't save the paste. The server returned an error when I clicked "Save this"

**Code sample**

```
resource "aws_s3_bucket" "bucket" {
	force_destroy = "true"
}

resource "aws_config_config_rule" "rule" {
	name = "config-rule-${random_id.id.hex}"

	source {
		owner             = "AWS"
		source_identifier = "S3_BUCKET_SERVER_SIDE_ENCRYPTION_ENABLED"
	}

	scope {
		compliance_resource_id = aws_s3_bucket.bucket.id
		compliance_resource_types = ["AWS::S3::Bucket"]
	}
}
```

**Screenshots**
image

**Additional context**
Terraform 0.12 adds support for [first-class expressions](https://www.hashicorp.com/blog/announcing-terraform-0-12#first-class-expression-syntax), so there is no need to use quotes.

Instead of ```compliance_resource_id = "${aws_s3_bucket.bucket.id}"```, ```compliance_resource_id = aws_s3_bucket.bucket.id``` is also correct, but the lexer highlights the dots as errors.

### PR DESCRIPTION
**Pull request by pyrmont**
Terraform 0.12 adds support for first-class expressions. Prior versions of Terraform required all non-literal expressions to be included as interpolated sequences inside strings.

In addition, the demo and visual samples have been rationalised. This will assist in future updates to the Terraform lexer.

This fixes #1301.

### CODE REVIEW

**Comment by pyrmont** [comment]
@sashee My solution was to add rules for certain punctuation characters to the `:hash` and `:array` states that the Terraform lexer inherits from the HCL lexer:

https://github.com/rouge-ruby/rouge/blob/30e1e8c25c17a05cba8c9579744360c74727d830/lib/rouge/lexers/hcl.rb#L113-L129

Another solution would be to add the rule to the `:root` state. Would this be preferable? Can expressions occur outside objects? I was afraid that adding to `:root` might have unintended consequences but perhaps there are situations outside of `:hash` and `:array` where first-class expressions should be permitted.

What do you think?

**Comment by sashee** [comment]
@pyrmont, I've just checked some of my terraform modules and I see another problem (I think it's related):

```
resource "aws_acm_certificate_validation" "cert" {
  certificate_arn         = "${aws_acm_certificate.cert.arn}"
  validation_record_fqdns = aws_route53_record.cert_validation[*].fqdn
}
```

The ```[*]``` part is reported as error, but that is valid.

If I wrap it in quotes: ```validation_record_fqdns = "${aws_route53_record.cert_validation[*].fqdn}"``` then it is not reported.

Apart from this issue all the other places are working fine now. I don't think expressions can occur outside objects.

**Comment by pyrmont** [comment]
@sashee Yeah, that's because I didn't add `*` to the character class that can match in a first-class expression. What characters should it include? I have `[.,()]`. Is `*` all I need to add?

**Comment by sashee** [comment]
Yes, I think the only special character is ```*```.

**Pull request merged**
