### PR TITLE
fix warning in Lexer

### PR DESCRIPTION
**Pull request by mojavelinux**
- don't reference undefined instance variable

### CODE REVIEW

**Comment by pyrmont** [comment]
What warning are you referring to here?

**Comment by mojavelinux** [comment]
Accessing an undefined instance variable, `@debug_enabled`.

**Comment by mojavelinux** [comment]
(You see this when adding the `-w` flag when invoking Ruby).

**Comment by mojavelinux** [comment]
Btw, the reason all the builds are failing is because the version of bundler is hardcoded in the Gemfile. This dependencies has no place in the Gemfile and should be removed. I'll submit a separate PR to address it.

**Comment by pyrmont** [comment]
@mojavelinux Can you push an empty commit? That'll trigger a new build by Travis.

**Comment by mojavelinux** [comment]
Done.

**Pull request merged**
