### PR TITLE
fixes #1760

### LINKED ISSUE #1760: Valid Kotlin syntax highlighted as error
**Name of the lexer**
kotlin

**Code sample**
A sample of the code that produces the bug.

```
// The ? is not an error
fun <T : Any> foo(a: Array<T?>): Int = a.size

// The < is not an error
val <T> T.exhaustive get() = this

// The . in Map.Entry is not an error
fun foo(props: Iterable<Map.Entry<String, JsonNode>>) = 
    TODO()
```

http://rouge.jneen.net/v3.26.1/kotlin/Ly8gVGhlID8gaXMgbm90IGFuIGVycm9yCmZ1biA8VCA6IEFueT4gZm9vKGE6IEFycmF5PFQ_Pik6IEludCA9IGEuc2l6ZQoKLy8gVGhlIDwgaXMgbm90IGFuIGVycm9yCnZhbCA8VD4gVC5leGhhdXN0aXZlIGdldCgpID0gdGhpcwoKLy8gVGhlIC4gaW4gTWFwLkVudHJ5IGlzIG5vdCBhbiBlcnJvcgpmdW4gZm9vKHByb3BzOiBJdGVyYWJsZTxNYXAuRW50cnk8U3RyaW5nLCBKc29uTm9kZT4-KSA9IAogICAgVE9ETygp

### PR DESCRIPTION
**Pull request by vidarh**

### CODE REVIEW

**Comment by tancnle** [comment]
@jneen Something's odd with the Travis build. It blocks merging across the repo. Could you kindly look into it? 🙏🏼

**Comment by jneen** [comment]
I swear I've removed it like three times now

**Comment by jneen** [comment]
I believe I've finally purged the project of Travis CI. I've also invited you to be a maintainer @tancnle :]

**Comment by tancnle** [comment]
Thank you for your prompt action on this @jneen ❤️ Really appreciated.

**Review by tancnle — APPROVED** [review]
Thank you for your contribution @vidarh ❤️ The change looks good to me 👍🏼

**Pull request merged**
