### PR TITLE
haskell: Properly highlight promoted data constructors

### PR DESCRIPTION
**Pull request by bgamari**
Unfortunately there is a bit of ambiguity with char literals.
For instance, the data constructor `A'` would be `'A'` in promoted form.
This will still be highlighted as as char literal but this is the best
we can do without more context.

### CODE REVIEW

**Comment by bgamari** [comment]
Ping.

**Comment by pyrmont** [comment]
@bgamari Sorry it's taken so long for a response. Could you add an example of this promotion to the visual sample?

**Comment by pyrmont** [comment]
@goolord Are you able to provide a code sample (just as a comment here is fine)? I'm not familiar enough with Haskell to try to write one on my own. I'm also not sure if the regex is correct. The regex as written requires a constructor to be at least two alphanumeric characters. Shouldn't it be fine just to have one?

**Comment by goolord** [comment]
i believe that's just to avoid ambiguity with char literals
img
here's some valid permutations of data constructors / promoted data constructors
since haskell is a context sensitive language, this seems like the best compromise to me. this is what i would expect in the absence of context, and it's certainly an improvement over the current highlighting

**Comment by pyrmont** [comment]
@goolord Thanks for the quick reply :) Makes sense. I think the regex should probably be the following:

rule /'[A-Z]\w+'?/, Keyword::Type  # promoted data constructor

**Comment by pyrmont** [comment]
Thanks @bgamari and @goolord for your help. This has been merged!

**Pull request merged**
