### PR TITLE
Fix lexing of line comments at EOF

### PR DESCRIPTION
**Pull request by MaximeKjaer**
This PR fixes Scala comments at EOF. See #797 for a previous instance of this problem.

### CODE REVIEW

**Comment by MaximeKjaer** [comment]
Actually, there are a few other lexers with the same problem. I'll fix them too, while I'm at it, and rename the PR.

**Comment by MaximeKjaer** [comment]
It turns out there are a few more of these than I expected. I've pushed my work so far, and will ping you when I've fixed all lexers that have this error.

**Comment by MaximeKjaer** [comment]
Those are all the occurrences I found of the same mistake! All fixed, and I added visual tests and a unit tests.

**Comment by pyrmont** [comment]
@MaximeKjaer Thank you so much for doing all this! I've know there were more of these lurking in the codebase for a while but just hadn't got around to cleaning them up. This PR is a real time saver!

I took the liberty of removing some of the extraneous regex operators that sometimes get thrown in (Ruby's regex engine will by default match to the end of the line so there's generally no need to explicitly mark that in the pattern, for instance). How does it look to you?

**Comment by MaximeKjaer** [comment]
That looks good! It really simplifies things nicely :+1:

**Comment by pyrmont** [comment]
Great! Thanks again for this! :tada:

**Pull request merged**
