### PR TITLE
Remove . as a operator in Python lexer

### LINKED ISSUE #1374: . shouldn't be an operator in Python
**Name of the lexer**
python.rb

**Code sample**
A sample of the code that produces the bug.

```python
import datetime.datetime

some_object.Method()
some_object.attribute

floats = (19.0, 19.)
```

**Additional context**
In rouge (and Pygments) `.` is treated as an operator

https://github.com/rouge-ruby/rouge/blob/7e04388a1222bf26ddb660778744eab82a6ea847/lib/rouge/lexers/python.rb#L86

resulting in e.g. pink dots in Monokai

image

The python [formal grammar](https://docs.python.org/3/reference/grammar.html) doesn't list `.` as an operator. Also other highlighters treat `.` as unhighlighted text, including sublime:

image

prism:
image

and github's highlighter:

image

### PR DESCRIPTION
**Pull request by ajnisbet**
Fixes #1374

### CODE REVIEW

**Comment by pyrmont** [comment]
Thanks for submitting this, @ajnisbet. This does look like an error in the way Pygments and Rouge approach things. Will have a review over the next few days and see!

**Comment by pyrmont** [comment]
@ajnisbet I made a change as removing the line that tokenised `.` as an `Operator` caused all dot-notation syntax to break.

My suggestion is that we add `.` to the list of punctuation:

https://github.com/rouge-ruby/rouge/blob/a2d870a8730e190f71dd84a5f143f19a3e3ae805/lib/rouge/lexers/python.rb#L79

In themes that render `Puncutation` tokens in the same colour as `Name` tokens, the two will be indistinguishable, but in themes where punctuation is highlighted in a different colour, that will continue to work.

Let me know your thoughts.

**Comment by ajnisbet** [comment]
Yeah that seems like a good solution!

**Comment by pyrmont** [comment]
@jneen I don't imagine you're a big Python user but do you have an opinion?

I'm hesitant to break ranks with Pygments (see [the relevant line](https://github.com/pygments/pygments/blob/29d2789f9fd3784652de2f20585db9a3fd9a7e76/pygments/lexers/python.py#L102) in their codebase)—especially given it _is_ a Python project—but tokenising `.` as `Operator` does seem to me to be incorrect given it's not an operator.

**Comment by pyrmont** [comment]
@ajnisbet Sorry it took so long to address this. This update will be part of the next version of Rouge which is scheduled for release on Tuesday 14 April. Thanks for the contribution!

**Pull request merged**
