### PR TITLE
Support type arguments in TSX

### PR DESCRIPTION
**Pull request by tancnle**
Add support for type arguments in TSX lexer

Screen Shot 2022-08-26 at 11 50 48 pm

Fixes https://github.com/rouge-ruby/rouge/issues/1833

### CODE REVIEW

**Comment by tancnle** [comment]
👋🏼 @intgr Could you help to validate if this addresses the reported issue? 🙏🏼

**Comment by intgr** [comment]
It would be hard for me to validate this. I noticed the issue in GitLab syntax highlighting, I don't use the Rouge library directly.

I can provide some more complicated test cases though:

```tsx
const render = () => (
  <>
    <MyComponent<Type1, Type2> attr={value} foo="bar" />
    <MyComponent<Omit<Type, 'field'>> attr={value} foo="bar" />
    <MyComponent<{field: string}> attr={value} foo="bar" />
    <MyComponent<{field1: Omit<Type1, 'field2'>}, Type2> attr={value} foo="bar" />
  </>
);
```

**Comment by intgr** [comment]
The screenshot you provided looks a bit weird.

image

The `<>` characters around `Type` have different colors. I would expect matching angle brackets to be the same color.

**Comment by tancnle** [comment]
> The screenshot you provided looks a bit weird.

Great catch 💯 The original mixin was incorrect as it does not render the content after the `<` correctly. I have updated the code and added your suggested test cases. Please let me know what you think 🙏🏼

**Comment by tancnle** [comment]
@intgr Heads up, I have split the addition of Typescript utility types to a separate [PR](https://github.com/rouge-ruby/rouge/pull/1865) and keep this just focusing on the type arguments support.

**Pull request merged**
