### PR TITLE
Add disambiguation for C++ header files

### LINKED ISSUE #932: C++ header files are not highlighted correctly
This issue originally occurred on [GitLab](https://gitlab.com/gitlab-org/gitlab-ce/issues/47647#note_80768758), which uses rouge for its syntax highlighting.

The problem is, that C++ header files with the file extension '.h' are highlighted as C files, even though that extension is very commonly used for C++ headers as well.

These following two snippets are from GitLab and highlighted by rouge.

Snippet 1, `example.h`: https://gitlab.com/snippets/1723020  
Highlighted as C code. Evident by the lack of highlighting of keywords such as `namespace`, `template`, `using` and `class`.

Snippet 2, `example.hpp`: https://gitlab.com/snippets/1723021  
Highlighted correctly as C++ code.

In comparison, an identical GitHub gist with name `example.h`: https://gist.github.com/eliaskosunen/4f508cdfb59aad0599c964ffa7ce9a87 is highlighted correctly as C++ code.

Possible solutions:
* Because for the most part, C++ is a superset of C, so header files with extension `.h` should probably default to C++ rather than C. The only keyword I can think of that exists in C but not in C++ is `restrict`, but there are way more examples the other way around
* Use some kind of heuristic to determine the language of header files

### PR DESCRIPTION
**Pull request by pyrmont**
C++ header files can use the `.h` extension. By default, Rouge highlights these files with the C lexer. This can lead to incorrect highlighting because certain keywords in C++ are not reserved in C. A similar situation can occur with Objective-C files but Rouge provides a disambiguation for Objective-C files to avoid this problem. This commit adds a similar disambiguation for C++.

This fixes #932.

### CODE REVIEW

**Comment by eliaskosunen** [comment]
The list of keywords could be improved. `bool` is technically a reserved word in C (it's a macro `#define`d to `_Bool` in the header `<stdbool.h>`), so that probably shouldn't be on the list. Other keywords that can appear at the beginning of a line present in C++ but absent in C include, off the top of my head:
 * `constexpr`
 * `try`, `catch` and `throw`
 * `protected`
 * `noexcept`
 * `static_cast`, `dynamic_cast` and `reinterpret_cast`
 * `virtual`
 * `this`
 * `typeid`
 * `thread_local`
 * `decltype`
 * `static_assert`
 * `alignas` and `alignof`
 * As of C++20, `concept`, `requires`, `co_await`, `co_async`, `co_yield` and `consteval`
and probably more

Whether these keywords should be used for detection, I don't know.

**Comment by pyrmont** [comment]
@eliaskosunen Thanks for the quick reply! Would some of those really begin a line in a header file (eg. `this`, `try`)? I think the key thing is to identify keywords that may be present in a header file on their own. Based on what I've seen, something like `namespace` meets this criterion whereas `typeid` doesn't. Of that list, I'm inclined to want to add `protected` (since I already added `public` and `private`) and `virtual`. But perhaps that's being too conservative?

**Comment by eliaskosunen** [comment]
Headers can contain `inline` function definitions, and with funky formatting, all of these could potentially appear at the beginning of a line:

```cpp
struct S {
  void foo() {
    try { // `try` as the first word of a line
      bar(
        this); // `this` as the first word of a line
    } catch(...) {
      // ...
    }
  }
};
```

Should you want to stay conservative, in the least I think you should have, in addition of what you listed, `constexpr` (appears frequently as the first word of a function signature in post-C++14-world), `try`, `catch` and `throw`.

**Comment by pyrmont** [comment]
@eliaskosunen Ah, forgot about inline function definitions. Hmmm... I think what I'd like to do at this point is release this fix and see how it goes in everyday use. What do you think?

**Comment by eliaskosunen** [comment]
This would certainly be better than what we have now.

**Comment by pyrmont** [comment]
@eliaskosunen Thanks for your help on this. We're on a two-week release cadence at the moment as we work through the backlog so this will go out as part of v3.8.0 on Tuesday 6 August. I'm not affiliated with GitLab at all so am not sure when they'll switch over to using it so you might want to check with them.

**Comment by jneen** [comment]
@eliaskosunen Back when I worked for Gitlab, I implemented this, which may be of interest to you: https://docs.gitlab.com/ee/user/project/highlighting.html

You can specify the language for any glob of files.

**Pull request merged**
