### PR TITLE
Feature: Add Dockerfile as an alias for the docker lexer.

### PR DESCRIPTION
**Pull request by ParamagicDev**
This allows users use:

\`\`\`Dockerfile

When specifying a filetype in their markdown.

### CODE REVIEW

**Review by jneen — APPROVED** [review]

**Comment by jneen** [comment]
Er, are we sure we don't downcase those tags? Maybe we should.

**Comment by ParamagicDev** [comment]
@jneen i tested it locally on a site I was building. It translates \`\`\`Dockerfile to `"language-Dockerfile"` so it doesn't appear to downcase as far as I can tell.

**Comment by jneen** [comment]
Hm. I don't think there is any compelling reason not to downcase it. Let's merge this for now and I'll start an issue to just downcase all tags and aliases transparently.

**Comment by jneen** [comment]
(That will have to be in v4, since it might break some code that relies on the "language-*" css classes)

**Pull request merged**
