### PR TITLE
Unicode update for Julia, XML, HTML, YAML, CSS and Javascript lexers.

### LINKED ISSUE #1534: Allow Unicode identifiers in several languages (Julia, XML, HTML, YML, CSS, JS, etc.)
Hello,

This topic was first created there: https://gitlab.com/gitlab-org/gitlab/-/issues/220566

But it seems it is based on Rouge, so I link the problem here. At least, the same problem occurs on the Rouge online tester.

Non-ASCII characters in identifier names break syntax highlighting in several languages, like Julia, XML, HTML, YML, CSS, Javascript…

I made a specific repository to show: https://gitlab.com/BenjaminGalliot/non-ascii-character-problem-test

I know there were some related issues opened and merged about Java and Python, so maybe it is a really more general issue.

Sincerely.

### PR DESCRIPTION
**Pull request by BenjaminGalliot**
Hello,

As you asked me in this [issue](https://github.com/rouge-ruby/rouge/issues/1534), I now make a PR. It was my first time to do some Ruby so I tried to be as conservative as possible, and following as much as possible the documentations and recommendations.

Edit: because it was not accepted yet, I added a minor correction.

Sincerely.

(This fixes #1534.)

### CODE REVIEW

**Comment by BenjaminGalliot** [comment]
OK, I made a small commit between to have a corrected and more accurate version and the last commit is the simplified one (more permissive on rare characters).

I kept the small commit because it is a kind of flag if one day someone bumps into a problem due to simplified version (so around \p{Me} and \p{No}, not normally in more complete and longer regexes but added by \p{Word})… 

If you think class substraction is not too hard to read (it seems Ruby 1.9+ allows it), you can try with it…

**Comment by pyrmont** [comment]
@BenjaminGalliot Thanks for making those changes. This looks good and I think that reads a easier. I don't think the subtraction is necessary (at least not until we here from people hitting problems caused by it).

I'll merge and this will be part of the v3.21.0 release that's scheduled to be pushed to RubyGems on Tuesday 14 July 🎉

**Comment by pyrmont** [comment]
@BenjaminGalliot Sorry—in my haste, I realised that this is missing examples. Could you add some simple examples to the visual samples for each language? These files are in `spec/visual/samples/` under the name of the lexer.

**Comment by BenjaminGalliot** [comment]
Added! Thank you!

**Comment by pyrmont** [comment]
@BenjaminGalliot Thanks for all your work on this PR. I've merged it in and it will be part of v3.21.0 of Rouge. That's set for release on Tuesday 14 July. I'm not sure when GitLab will start using it but they're usually pretty good at updating to the latest gem so I don't expect it will take too long. Thanks again! 🎉

**Pull request merged**
