### PR TITLE
Add missing keywords to LLVM lexer

### LINKED ISSUE #1502: Missing keywords in LLVM lexer
**Name of the lexer**
LLVM Lexer.

**Code sample**
I'm using Rouge from Jekyll.
A sample of the code that produces the bug:

```
source_filename = "main.ura"
```

Screenshot_2020-04-15_13-13-42

More info about `source_filename` in the [LLVM LangRef][llvmDoc].

**Additional information**

Apart from that keyword, which is the only failure I've found so far, I read the [Pygments LLVM lexer][lexer] and I observed that it contains a lot more keywords.
I computed the difference between the Rouge keywords + instructions + types and the Pygments ones and I get 162 words that are not present in Rouge but present in Pygments:
```
['acq_rel', 'acquire', 'afn', 'aliasee', 'alignLog2', 'allOnes', 'amdgpu_cs', 'amdgpu_es', 'amdgpu_gs', 'amdgpu_hs', 'amdgpu_kernel', 'amdgpu_ls', 'amdgpu_ps', 'amdgpu_vs', 'any', 'anyregcc', 'args', 'atomic', 'atomicrmw', 'avr_intrcc', 'avr_signalcc', 'bit', 'bitMask', 'blockaddress', 'branchFunnel', 'byArg', 'byte', 'byteArray', 'callee', 'caller', 'calls', 'catchpad', 'catchret', 'catchswitch', 'cleanuppad', 'cleanupret', 'cmpxchg', 'comdat', 'contract', 'critical', 'cxx_fast_tlscc', 'deplibs', 'dereferenceable', 'dereferenceable_or_null', 'distinct', 'dsoLocal', 'dso_local', 'dso_preemptable', 'exactmatch', 'externally_initialized', 'fence', 'filter', 'flags', 'from', 'funcFlags', 'function', 'ghccc', 'guid', 'gv', 'hash', 'hhvm_ccc', 'hhvmcc', 'hot', 'hotness', 'ifunc', 'immarg', 'inalloca', 'indir', 'indirectbr', 'info', 'initialexec', 'inline', 'inlineBits', 'inrange', 'insts', 'intel_ocl_bicc', 'inteldialect', 'kind', 'largest', 'linkage', 'live', 'local_unnamed_addr', 'localdynamic',
'localexec', 'max', 'min', 'monotonic', 'msp430_intrcc', 'musttail', 'name', 'nand', 'noRecurse', 'noduplicates', 'none', 'nonnull', 'notEligibleToImport', 'notail', 'offset', 'path', 'prefix', 'preserve_allcc', 'preserve_mostcc', 'prologue', 'readNone', 'readOnly', 'reassoc', 'refs', 'relbf', 'release', 'resByArg', 'returnDoesNotAlias', 'returned', 'samesize', 'seq_cst', 'single', 'singleImpl', 'singleImplName', 'sizeM1', 'sizeM1BitWidth', 'source_filename', 'spir_func', 'spir_kernel', 'summaries', 'summary', 'swiftcc', 'swifterror', 'swiftself', 'syncscope', 'token', 'typeCheckedLoadConstVCalls', 'typeCheckedLoadVCalls', 'typeIdInfo', 'typeTestAssumeConstVCalls', 'typeTestAssumeVCalls', 'typeTestRes', 'typeTests', 'typeid', 'umax', 'umin', 'uniformRetVal', 'uniqueRetVal', 'unknown', 'unordered', 'unsat', 'uselistorder', 'uselistorder_bb', 'vFuncId', 'variable', 'virtualConstProp',
'webkit_jscc', 'willreturn', 'win64cc', 'within', 'wpdRes', 'wpdResolutions', 'x86_64_sysvcc', 'x86_intrcc', 'x86_mmx', 'x86_regcallcc', 'x86_thiscallcc', 'x86_vectorcallcc', 'xchg']
```

[lexer]: https://github.com/pygments/pygments/blob/e10c53ac1214de8e79e4582ba85b0dba046731ee/pygments/lexers/asm.py#L345
[llvmDoc]: https://releases.llvm.org/10.0.0/docs/LangRef.html#source-filename

### PR DESCRIPTION
**Pull request by pyrmont**
There are a number of keywords missing from the LLVM lexer. This PR adds them to the appropriate group.

It fixes #1502.

### CODE REVIEW

**Comment by pyrmont** [comment]
@guiferviz Thanks for the bug report. I had a look through the page you linked and I couldn't find the following keywords that you extracted from the Pygments lexer. Are these mistakes?

```
avr_intrcc
avr_signalcc
deplibs
function
ghccc
hhvm_ccc
hhvmcc
inline
intel_ocl_bicc
msp430_intrcc
none
spir_func
spir_kernel
unknown
variable
win64cc
x86_64_sysvcc
x86_intrcc
x86_regcallcc
x86_thiscallcc
x86_vectorcallcc
```

**Comment by guiferviz** [comment]
@pyrmont Thanks for your work.
You mean the link of the [LLVM LangRef](https://releases.llvm.org/10.0.0/docs/LangRef.html#source-filename), right?

Unfortunately I'm not an LLVM expert and I can't tell you 100% sure what all those keywords are for.
I know some of them are [calling conventions](https://en.wikipedia.org/wiki/Calling_convention), very specific to the machine you're generating the code for. That's why I think they are not in the LLVM LangRef. LLVM's documentation is not particularly complete. It is a documentation that is made for people who already know how to use the tool :rofl:

I've found this [code](https://llvm.org/doxygen/AsmWriter_8cpp_source.html#l00344) that generates LLVM IR code (the code we are trying to highlight).

Also, if you search for those words in the LLVM repository maybe you get a *.ll file with those keywords. *.ll is the extension of LLVM IR code. For example, in [this link](https://github.com/llvm/llvm-project/search?q=x86_vectorcallcc&unscoped_q=x86_vectorcallcc) you will see all the files with `x86_vectorcallcc` in the LLVM repository.
I didn't check all of them though.

We can:
* Rely on Pygments keywords.
* Check if all the keywords are in a *.ll file in the LLVM repository.
* Wait for someone to open a new bug :)

**Comment by guiferviz** [comment]
Maybe I write to you so fast... I've just found [this lexer](https://github.com/llvm/llvm-project/blob/master/llvm/lib/AsmParser/LLLexer.cpp). It's the official LLVM lexer for reading *.ll files!
It contains all those keywords.

**Comment by pyrmont** [comment]
@guiferviz Thanks for finding that lexer file. I wrote a Rake task that will automatically generate the keywords and put them into a file that can then be loaded as needed. How does it look?

**Comment by guiferviz** [comment]
It looks terrific! Now we are sure that it contains all the keywords.
I can't do a technical review of the code because I just learned what Rack is, but I checked that the generated keywords are in the Pygements lexer. We now even have 21 more keywords than the Pygments lexer!
Thank you so much!

**Comment by pyrmont** [comment]
@guiferviz Thanks for your help on this! This will be part of the next version of Rouge: v3.19.0. That's scheduled for release on Tuesday 12 May. Thanks again!

**Comment by guiferviz** [comment]
@pyrmont Thanks for your time!

**Pull request merged**
