### PR TITLE
Support doctest in Python lexer

### PR DESCRIPTION
**Pull request by tancnle**
Add support to highlight [`doctest`](https://docs.python.org/3/library/doctest.html?highlight=doctest#module-doctest) in Python lexer.

| Before | After |
| -- | -- |
|before |  after | 

Resolves https://github.com/rouge-ruby/rouge/issues/920

### CODE REVIEW

**Comment by tancnle** [comment]
👋🏼 @Erotemic could you verify if this addresses the reported issue? 🙏🏼

**Comment by Erotemic** [comment]
This looks great! 

I'm perfectly happy with this as-is. The only thing I might suggest is that the "want" part of the doctest where you specify the expected result would be more readable if it was distinguished from the rest of the string by a different color. For example vim does it this way: 

image

The logic would be that a "want" statement starts after the last `>>> ` or `... ` prefix and ends whenever there is a blank newline.

However, if that's difficult to implement, then this addresses 99% of the problem and is a huge readability improvement!  I can't wait to be able to read my doctests on gitlab!

**Comment by tancnle** [comment]
Thank you for the insights @Erotemic. I have rejigged the PR to provide better support for test output. I have also ensured the lexer can distinguish between `...` as a prompt and a builtin.

**Comment by tancnle** [comment]
>  I can't wait to be able to read my doctests on gitlab

I believe GitLab only uses Rouge for language detection, not for syntax highlighting. It has switched to Highlight JS for syntax highlighting (see [doc](https://docs.gitlab.com/ee/user/project/highlighting.html)).

**Comment by Erotemic** [comment]
> Let me know what you think.

That looks much better. I would call this feature complete.

> It has switched to Highlight JS for syntax highlighting (see [doc](https://docs.gitlab.com/ee/user/project/highlighting.html)).

Ah, good to know. Well more doctest support in general is better, so thank you for implementing this.

**Pull request merged**
