### PR TITLE
Remove errors in samples

### PR DESCRIPTION
**Pull request by miparnisari**
I ran the samples of each language, and if the output of `document.querySelectorAll("span.err")` gave errors, I fixed those. Most errors were caused by multi line strings or comments: their regexes weren't matching newlines.

Also fixed the fact that if you loaded `liquid?debug` you got an error.

### CODE REVIEW

**Comment by pyrmont** [comment]
@miparnisari I don't think the fact that samples include errors means that the samples need to be corrected. It may be intentional to have a sample include an error to show how errors are highlighted.

What's the `liquid?debug` error that you're referring to? That sounds like something that's a problem.

**Comment by ashmaroli** [comment]
> What's the `liquid?debug` error that you're referring to?

@pyrmont I think she's referring to the visual test:
1. Start the visual test app and navigate to `http://localhost:9292/liquid`
2. Now navigate to `http://localhost:9292/liquid?debug` or `http://localhost:9292/liquid?debug=true`

**Comment by pyrmont** [comment]
@ashmaroli Thanks. I've submitted #1192 with an alternative fix.

**Comment by pyrmont** [comment]
Thanks for taking the time to submit the fix, @miparnisari. I'm sorry it sat there for so long and now I'm closing it :( I hope it doesn't discourage you from making future submissions!

**Pull request closed without merging**
