### PR TITLE
Add :test group to Gemfile

### PR DESCRIPTION
**Pull request by pyrmont**
As discussed in #1137, this adds a `:test` group to the Gemfile.

### CODE REVIEW

**Comment by pyrmont** [comment]
Hmmm. I'm not sure why this is failing. Any ideas @ashmaroli?

**Comment by pyrmont** [comment]
@ashmaroli Oh, and given @jneen's comment that the Gemfile dependencies are all for development, maybe the `:test` group is superfluous and it's not necessary to group these gems (I'd still like to know why this is failing).

What do you think?

**Comment by ashmaroli** [comment]
@pyrmont When you add a gem to a Bundler group, you've to explicitly require it. The following patch to `spec/spec_helper.rb` should resolve the issue:
```diff
  require 'minitest/spec'
  require 'minitest/autorun'
+ require 'minitest/power_assert'

**Comment by ashmaroli** [comment]
> maybe the `:test` group is superfluous

Bundler groups are only really helpful if you need to "handle" certain gems with special treatment (like not installing them with the `--without` switch or auto-require gems internally..), otherwise they're just aides for organizing long lists of gems.

**Comment by pyrmont** [comment]
Yep, I agree. I'll close this request.

**Pull request closed without merging**
