### PR TITLE
Add missing C++11/14 syntax (binary numbers, time literals, variadic templates)

### PR DESCRIPTION
**Pull request by rongjiecomputer**
Note: binary literal (line 5), time literal (line 20-27) and variadic template (line 81-84, 119) are not highlighted correctly.

### CODE REVIEW

**Comment by jneen** [comment]
Thanks for this! I'll try to find some time to work on supporting all this soon.

**Comment by pyrmont** [comment]
For comparison, [here](https://gist.github.com/pyrmont/0010c3f3f1ba8aa09baf707a9bece4ff) is how GitHub highlights the visual sample.

**Comment by pyrmont** [comment]
@rongjiecomputer Sorry this has been outstanding for such a long time. I'm not sure if you're still interested, but I've rebased this against the current master and added the missing syntax. I'm not very familiar with C++ so am not sure if this looks like it should; there are no error tokens and it looks to my eyes broadly consistent with [GitHub's highlighting](https://gist.github.com/pyrmont/0010c3f3f1ba8aa09baf707a9bece4ff).

**Comment by rongjiecomputer** [comment]
@pyrmont looks good!

**Comment by pyrmont** [comment]
Well, it took three years and I screwed up the commit message but we did it @rongjiecomputer! Rouge will now be able to kick 3.5% more ass when highlighting C++ :D

**Pull request merged**
