### PR TITLE
Add highlighting of block chomping in YAML text

### PR DESCRIPTION
**Pull request by ashmaroli**
YAML Visual Test

### CODE REVIEW

**Comment by pyrmont** [comment]
What's 'block chomping' mean in this context?

**Comment by ashmaroli** [comment]
> What's 'block chomping' mean in this context?

Sorry about not giving proper context @pyrmont 
You'll find the necessary information at the following: https://yaml-multiline.info/

**Comment by pyrmont** [comment]
[ohmygodyamlisinsane](https://stackoverflow.com/a/21699210/)

**Comment by ashmaroli** [comment]
> *There are 5 6 NINE (or 63*, depending how you count) different ways to write multi-line strings in YAML.*

Oh wow..! :sweat_smile:

**Comment by pyrmont** [comment]
Farewell 1234! Until we meet again in PR/issue 12345!

**Pull request merged**
