### PR TITLE
 Release v3.28.0

### PR DESCRIPTION
**Pull request by tancnle**

### CODE REVIEW

**Comment by tancnle** [comment]
@jneen Would it be possible if you could add me to the list of gem owners so I can publish a new release? 🙏🏼

**Comment by tancnle** [comment]
@rouge-ruby/maintainers can anyone with admin access to rouge gem help me with the above request?

**Comment by dblessing** [comment]
@tancnle Done. Thanks for your help with Rouge

**Comment by tancnle** [comment]
Thank you @dblessing. v3.28.0 gem has been released (https://rubygems.org/gems/rouge/versions/3.28.0).

**Pull request merged**
