### PR TITLE
added *.Dockerfile filename extension

### LINKED ISSUE #1058: .Dockerfile extension
Although dockerfile highlighting was [added](https://github.com/jneen/rouge/issues/455), the `.Dockerfile` extension was not.

### PR DESCRIPTION
**Pull request by webmaster777**
closes #1058

### CODE REVIEW

**Comment by webmaster777** [comment]
I'm having issues with the bundler version required in the Gemfile and the one being used in the travis builds. I'm not sure how to fix this or whether it might have something to do with caching.

This problem also occurs with other resent PRs.

**Comment by webmaster777** [comment]
Funny this is that even though i made the version explicit, it still uses a different version:

(from the build output)

~~~
$ gem install bundler -v 1.17.2
Fetching: bundler-1.17.2.gem (100%)
Successfully installed bundler-1.17.2
1 gem installed
before_install.2
2.90s$ gem update --system
Updating rubygems-update
Fetching: rubygems-update-3.0.2.gem (100%)
Successfully installed rubygems-update-3.0.2
Installing RubyGems 3.0.2
Bundler 1.17.3 installed
RubyGems 3.0.2 installed
Regenerating binstubs
[..snip..]
RubyGems installed the following executables:
	/home/travis/.rvm/rubies/ruby-2.3.7/bin/gem
	/home/travis/.rvm/rubies/ruby-2.3.7/bin/bundle
RubyGems system software updated
$ bundle install --without development --path=${BUNDLE_PATH:-vendor/bundle}
Fetching gem metadata from http://rubygems.org/........
Fetching gem metadata from http://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    bundler (~> 1.15)
  Current Bundler version:
    bundler (2.0.1)
~~~

**Comment by vidarh** [comment]
@webmaster777 I've submitted a PR (#1062) to set the specific bundler version, and remove the older Rubies from the CI setup and that works. I've asked @dblessing to confirm if he's ok with that approach. If not I'll see if there's another way of resolving this for the older Ruby versions.

**Comment by pyrmont** [comment]
@webmaster777 I don't mean to make it sound like I'm playing you off against each other, but would you be able to update this to cover the additional case described in #1070? I'll merge in whichever is completed first.

**Comment by webmaster777** [comment]
Like this?

**Comment by pyrmont** [comment]
Just like that :)

**Pull request merged**
