### PR TITLE
Fixes #947: Add documentation on using Docker for development

### LINKED ISSUE #947: Add a wiki page with Docker instructions for development
Similar to #733 I've been using Docker for development to avoid having to install Ruby and all the dependencies. Accepting #733 would make sense IMHO and help getting new people on board, but as an alternative I wrote instructions on how to use Docker with ad-hoc commands: https://gist.github.com/nguillaumin/a3f41095e735eb10112afa9c0e970893

If that's of interest it could be added as a wiki page next to the other guides. If not, then feel free to close this :)

### PR DESCRIPTION
**Pull request by nguillaumin**

### CODE REVIEW

**Comment by pyrmont** [comment]
@nguillaumin Thank you for contributing this. I have a couple of tweaks I want to make (partly in other docs that should cross reference this) so I'm sorry that's taking a while. 

I did have a question generally, though. While I think having instructions to install through Docker is a good idea and I definitely want to include this, I was curious what you were referring to as 'dependencies'.

Maybe this is just my personal experience, but I've found Docker itself to generate many more dependencies to install and manage than Ruby. I understand you could mean the gem dependencies but these can be managed by having Bundler install into a directory within the project (which is in fact what you do with your Docker tasks).

The obvious counterargument was production systems. But is that what you had in mind?

**Comment by pyrmont** [comment]
@nguillaumin I hope this isn't too forward but I've pushed some changes directly to your branch. I've expanded and revised the wording, added cross references and inserted newlines into the text so that it wraps at 80 characters.

Please let me know what you think!

**Comment by nguillaumin** [comment]
Sorry didn't have time to reply earlier.

What I meant by dependencies is Ruby and everything that comes with it. I don't use Ruby generally so I don't necessarily want to install it on my system and everything that goes with it. For example I don't even know exactly what Bundler is :wink:

I think you captured that we'll with your changes, so I'm fine with them. Thanks!

**Comment by pyrmont** [comment]
Thanks for the submission, @nguillaumin! It should start appearing on RubyDocs after their next scheduled rebuild :)

**Pull request merged**
