### PR TITLE
Add lexer for Zig lang

### PR DESCRIPTION
**Pull request by timmyjose**
Subsumes and overrides https://github.com/rouge-ruby/rouge/pull/1525. That PR had been created from a different organisation (belonging to me), but apparently Github does not allow edits from maintainers for such repos, only for "user-owned" repos.

### CODE REVIEW

**Comment by timmyjose** [comment]
@pyrmont As mentioned above, this PR is identical to https://github.com/rouge-ruby/rouge/pull/1525, but created from my own account due to Github's strange behaviour. 

You should be able to push commits to this branch now. Thanks!

**Comment by pyrmont** [comment]
@timmyjose Let me know if the changes make sense or if there is anything else that is unclear!

**Comment by timmyjose** [comment]
@pyrmont Thanks for the cleanup and changes! It looks good from my side. Cheers.

**Comment by pyrmont** [comment]
@timmyjose Thanks for the submission! This has been merged in and will be part of v3.20.0 of Rouge. That's scheduled for release on Tuesday 9 June 🎉

**Pull request merged**
