### PR TITLE
Fix & selector in Sass/SCSS lexer

### LINKED ISSUE #841: SCSS and Sass give errors with `::` (pseudo-element) in selector
[SCSS](http://rouge.jneen.net/pastes/Vwz6)

image

[Sass](http://rouge.jneen.net/pastes/xXq0)

image

### PR DESCRIPTION
**Pull request by pyrmont**
The `&` selector does not match correctly if it is combined with certain characters. This PR fixes the problem by adding a rule matching `&` to `:content_common`.

It fixes #841.

### CODE REVIEW

**Comment by pyrmont** [comment]
@AlexWayfer I wouldn't blame you if you've moved on but just wanted to let you know that this appears to fix the bug you identified in Rouge's handling of `&` in Sass/SCSS selectors.

**Comment by AlexWayfer** [comment]
> @AlexWayfer I wouldn't blame you if you've moved on but just wanted to let you know that this appears to fix the bug you identified in Rouge's handling of `&` in Sass/SCSS selectors.

OK, thank you, no problem. I'm disappointed that there is still no notifications about related PRs at least in the same repository.

Again, thank you. I still use SCSS sometimes and Rouge, especially on GitLab.

**Comment by pyrmont** [comment]
@AlexWayfer Yeah, that is strange that GitHub doesn't automatically notify you if a PR is marked as resolving an issue. Glad I tagged you.

I've merged this in and it will be part of v3.21.0 of Rouge when that comes out on Tuesday 14 July. I'm not sure of when GitLab will update the version of Rouge they're running but they're usually pretty quick. Sorry again for the wait!

**Comment by AlexWayfer** [comment]
> Sorry again for the wait!

No problem, thank you for fix and merge!

**Pull request merged**
