### PR TITLE
add HTMLLineanchors formatter

### PR DESCRIPTION
**Pull request by m-cat**
* also add `lineanchors` and `linewise` options to HTMLLegacy

Since Rouge is the default highlighter in Jekyll, I wanted to add the option to use `lineanchors` for improved compatibility with another popular syntax highlighter (and the previous default in Jekyll), Pygments. It looks like there was no existing formatter I could use -- I wanted an anchor before each line, but linewise wraps the entire line in a div.

This formatter is not very useful apart from compatibility, because line anchors don't really belong in code blocks. If you have more than one code block, then an anchor like "line-1" is ambiguous, and kind of useless. Still, people on the internet [seem to use it](https://drewsilcock.co.uk/proper-linenumbers).

I added a `lineanchors` option to the HTMLLegacy formatter, which is the default in Jekyll. I also added a `linewise` option to use the existing HTMLLinewise formatter, which I think is better. If this goes through, I'll be raising a separate PR in the Jekyll repo to enable these options.

### CODE REVIEW

**Comment by m-cat** [comment]
Doth my eyes deceive me...? Has a mortal soul at long last glimpsed this PR?

Here's some more context: [my blog post](https://www.bytedude.com/jekyll-syntax-highlighting-and-line-numbers/#giving-up-the-gun), [Jekyll plugin that implements this](https://github.com/m-cat/highlight-linedivs).

**Comment by pyrmont** [comment]
I'm sorry there hasn't been much movement on this since it was submitted. There's renewed work being done on looking at outstanding PRs and hopefully the backlog will start being cleared soon.

I'm trying to help look through things and had a couple of questions:

1. Does it makes sense to allow the HTMLLineanchors formatter to be referenced from the HTMLLegacy formatter? Per the README:
   
   > `Rouge::Formatters::HTMLLegacy.new(opts={})` is a backwards-compatibility class intended for users of rouge 1.x, with options that were supported then.
   
   It seems to me that a formatter that's being added in version 3 isn't something that users of Rouge 1.x would expect to be available.

2. Since this PR was submitted, #1085 has been submitted. There's been discussion in that PR about allowing for the HTML tag to be configurable (as is the case in #1090). If that were implemented, would that obviate the need for this PR?

**Comment by m-cat** [comment]
Hey Michael! Thanks for taking a look. Glad the project is moving forward! I'll get back to your questions in a couple of days, thanks.

**Comment by pyrmont** [comment]
@m-cat I'm closing this PR as the new HTMLLineTable formatter added via #1211 should cover it adequately. While it does not add `<a>` elements as in the solution proposed here, it does add `id` attributes to the containers holding individual lines. These attributes allow for linking to elements within an HTML page (see [the HTML5 spec](http://www.w3.org/html/wg/drafts/html/master/browsers.html#scroll-to-fragid) and [this discussion on StackOverflow](https://stackoverflow.com/q/484719/308909)).

Oh, and it's worth noting that the issue of whether the HTMLLegacy formatter should be updated came up in that PR and [the eventual decision](https://github.com/rouge-ruby/rouge/pull/1211#discussion_r299817708) was that it should not.

**Pull request closed without merging**
