### PR TITLE
port bw style from Pygments to Rouge

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by pyrmont** [comment]
I think this PR needs to add the theme to the relevant section of [`lib/rouge.rb`](https://github.com/jneen/rouge/blob/e957c740ca85b3a96f2cea1e8e1eafbf9cb2abc4/lib/rouge.rb#L73-L84).

**Comment by mojavelinux** [comment]
Thanks for pointing that out. I'll update accordingly.

**Comment by mojavelinux** [comment]
I've updated as requested. I verified using the visual app that the theme loads by name only.

**Comment by mojavelinux** [comment]
Thanks for merging!

**Pull request merged**
