### PR TITLE
added basic Haxe support (part 2)

### PR DESCRIPTION
**Pull request by RichardBray**
Haxe is such a cool language but currently isn't supported by Rogue. Hopefully, this PR will fix that.
Much of these code changes have been done by @josuigoa, I only worked on the samples file.

### CODE REVIEW

**Comment by pyrmont** [comment]
@RichardBray So this is just the code in #815 but with different samples? It'd be better to update the code in that PR so that we can keep all the conversation in one place. I'm guessing you don't have commit rights to @josuigoa's fork?

**Comment by RichardBray** [comment]
@pyrmont Yep, unfortunately, I don't have the commit rights :( 
I guess we could wait till he is back from vacation or hope he ticked the 'allow edits from maintainers' checkbox.

**Comment by pyrmont** [comment]
No worries. I think I do have access so I'll try to submit a patch myself with these changes and see how it goes :) Will keep you posted!

**Comment by RichardBray** [comment]
@pyrmont Thanks 👍

**Comment by RichardBray** [comment]
This isn't needed anymore, my changes have been merged into https://github.com/rouge-ruby/rouge/pull/815

**Pull request closed without merging**
