### PR TITLE
use require_relative instead of load_lexer based on Kernel.load

### PR DESCRIPTION
**Pull request by gfx**
Just use the built-in `require_relative` instead of custom loading methods.

### CODE REVIEW

**Comment by gfx** [comment]
OMG. `__dir__` is not defined in Ruby 1.9. Waiting for #775, too.

**Comment by jneen** [comment]
Please make sure `Rouge.reload!` continues to function properly - the development server depends on it.

**Comment by jneen** [comment]
Oh, I see you've replaced it with `Rack::Reloader`. Then the important thing is to make sure https://github.com/jneen/rouge.jneen.net/blob/master/app/models/rouge_version.rb continues to work

**Comment by gfx** [comment]
I didn't see https://github.com/jneen/rouge.jneen.net before, but yes I'll check it with a new version of rouge.

Hopefully the rouge CI checks rouge.jneen.net too 🤔

**Comment by pyrmont** [comment]
@gfx Is this still something worth bringing into Rouge? There's been numerous changes since this PR and I'm not sure whether it has any benefits.

**Comment by gfx** [comment]
@pyrmont Thanks for remembering it with me. I believe using `require_relative` is still useful for all the ruby projects, but this PR is too old, so I'll close it for now.

**Pull request closed without merging**
