### PR TITLE
Fix comment parsing in Console lexer 

### LINKED ISSUE #1370: Please document usage of console options (e.g. ?prompt, ?root, etc.)
I'm trying to make use of the console lexxer option as described at <https://github.com/rouge-ruby/rouge/blob/master/CHANGELOG.md> and <https://github.com/rouge-ruby/rouge/wiki/List-of-supported-languages-and-lexers>. But whatever I do, I don't see any difference and I even don't have any clue, when and what they would alter. I presume, that the usage is

> \`\`\`console?option=value
> 
> \`\`\` 

But it doesn't change anything, e.g. both the following examples lead to the same result.

> \`\`\`console?root=1
> \# foobar
> \`\`\` 

> \`\`\`console?comments=1
> \# foobar
> \`\`\` 

altough they have different meanings. Please document the options and the correct usage.

### PR DESCRIPTION
**Pull request by pyrmont**
The Console lexer would not correctly parse comments if only the `comments` option was enabled. This was because of a bug in the way the prompt regular expression pattern. This PR fixes that bug and adds a series of tests to confirm the behaviour of the lexer is as intended.

This fixes #1370.

### CODE REVIEW

**Comment by pyrmont** [comment]
@dleidert Progress was delayed by a few things but I think I finally found the bug. I've patched that in this PR and added some tests to confirm this. Can you see how it looks on your end?

**Comment by jneen** [comment]
Good catch!

**Comment by pyrmont** [comment]
@jneen Always feels good to squash a bug! :)

**Comment by dleidert** [comment]
I can confirm that using e.g. `console?comments=1` works. All these produce the same result:

```
console?comments
console?comments=1
console?comments=true
console?comments=false
```

Only `console?comments=0` restores the same behavior as `console?prompt=#`. If both options are used, `prompt` seems to override the `comments` option independent of the order.

**Comment by pyrmont** [comment]
@dleidert Hmmm.... that `comments=false` result seems wrong, doesn't it? I think I can imagine why it's happening but it's not what the user would expect. I might file that as a separate bug and look into fixing it.

As for the order not mattering, that's the behaviour working as intended. The way the Console lexer works is that it will [first¹ attempt](https://github.com/rouge-ruby/rouge/blob/e2b6fd920abebe80974efb3cc88c6c90da47b251/lib/rouge/lexers/console.rb#L114) to match each line against the `@prompt_regex` regex pattern. When the prompt is set to `#`, that pattern is `/[^<#]*?#/`. Since the prefix (`[^<#]*?`)can match zero or more times, for any line that begins with a `#`, the prefix will match zero times and the ending character (`#`) will match once and it'll be treated as a prompt.

 ¹ As you can see when you follow the link, what it _actually_ checks first is whether there's an elision (as now described in [this code comment](https://github.com/rouge-ruby/rouge/blob/e2b6fd920abebe80974efb3cc88c6c90da47b251/lib/rouge/lexers/console.rb#L105-L107)).

I've made an additional commit that adds some documentation to the beginning of the class that hopefully explains things a bit better. How does it look?

**Comment by dleidert** [comment]
> @dleidert Hmmm.... that `comments=false` result seems wrong, doesn't it?

That's what I thought.

> As for the order not mattering, that's the behaviour working as intended. [..]

Ok. Makes sense. This is probably more a matter of documenting the behavior.
 
> I've made an additional commit that adds some documentation to the beginning of the class that hopefully explains things a bit better. How does it look?

Looks good to me :) Would be nice to have something like this at <https://github.com/rouge-ruby/rouge/wiki/List-of-supported-languages-and-lexers> or a sub-site for the console lexer. I can add it myself if you want me.

**Comment by pyrmont** [comment]
@dleidert wrote:

> Would be nice to have something like this at https://github.com/rouge-ruby/rouge/wiki/List-of-supported-languages-and-lexers or a sub-site for the console lexer. I can add it myself if you want me.

I think adding it to the wiki is probably best for now. Speaking personally (and not for the other maintainers), I would like to have all documentation be centralised at [rouge-ruby.github.io/docs/](https://rouge-ruby.github.io/docs/) and trash the wiki but even if we eventually decide to move in that direction, it would be a large scale effort and, in the meantime, having up to date information on the wiki seems like the smart move.

I should note that, in case it wasn't obvious, [the docs for the ConsoleLexer class](https://rouge-ruby.github.io/docs/Rouge/Lexers/ConsoleLexer.html) will be updated but that won't happen until with the next release of Rouge on Tuesday 14 January.

**Pull request merged**
