### PR TITLE
Pre-generate builtins and keywords for lexers

### PR DESCRIPTION
**Pull request by ashmaroli**
Instead of loading a YAML file and computing the sets from the data at runtime, to reduce memory usage.

### CODE REVIEW

**Comment by ashmaroli** [comment]
### Memory profile summary
```diff
--- master https://travis-ci.org/rouge-ruby/rouge/jobs/642229408
+++ PR     https://travis-ci.org/rouge-ruby/rouge/jobs/643419479

- Total allocated: 14.70 MB (142309 objects)
+ Total allocated: 13.53 MB (132177 objects)
- Total retained:  5.31 MB (37531 objects)
+ Total retained:  5.09 MB (35512 objects)
```

**Comment by pyrmont** [comment]
@ashmaroli Thanks for this—that looks like a nice little reduction. Do you see any issues, @jneen?

**Comment by ashmaroli** [comment]
@jneen Requesting your feedback on this so that it can be included in the upcoming release.
Thank you.

**Comment by ashmaroli** [comment]
Will this get included in the upcoming release..?

**Comment by pyrmont** [comment]
@ashmaroli Sorry, still waiting for @jneen's feedback.

**Comment by ashmaroli** [comment]
### Memory profile summary
```diff
--- master https://travis-ci.com/github/rouge-ruby/rouge/jobs/318551844
+++ PR     https://travis-ci.com/github/rouge-ruby/rouge/jobs/318777292

- Total allocated: 14.14 MB (141625 objects)
+ Total allocated: 13.07 MB (132473 objects)
- Total retained:  5.44 MB (37843 objects)
+ Total retained:  5.22 MB (35959 objects)
```

**Comment by pyrmont** [comment]
@ashmaroli I think this has been in review for long enough. I'm happy to merge this but is there anything else you wanted to add or is it ready from your side, too?

**Comment by pyrmont** [comment]
@ashmaroli Perhaps I should revert the most recent commits but I thought it might be handy to have a single task that runs all the builtin generators but in the course of testing it, came across a bunch of bugs in some of the current Rake tasks. I've fixed those and generated new builtin files.

What do you think?

**Comment by ashmaroli** [comment]
@pyrmont I think its a good idea to have a *One Task to ~~rule~~ generate them all..* :wink: 

But if the additional changes are going to push this PR to be included in the next month's release rather than today's, I feel it'd be better if the new changes were in a separate PR so that if I were asked to make changes to this proposal at a future date, then it'd be easier for me if I didn't have to wrap my head around your changes as well...

**Comment by pyrmont** [comment]
Yeah, fair enough. Will revert.

**Comment by pyrmont** [comment]
Thanks for the PR, @ashmaroli. I'll open a separate one for the generate task.

**Comment by ashmaroli** [comment]
Thank you very much @pyrmont :)

**Pull request merged**
