### PR TITLE
Add PostScript lexer

### PR DESCRIPTION
**Pull request by ljcooke**
This adds a lexer for PostScript.

The bulk of the work was done in #1092. I've cherry-picked the changes involving PostScript, and fixed some bugs with keyword and filetype detection.

### CODE REVIEW

**Comment by pyrmont** [comment]
@ljcooke Thanks for this! Sorry to have been a bit quiet the past couple of weeks. Am still a bit knee deep in another project but will review this as soon as possible :)

**Review by pyrmont — CHANGES_REQUESTED** [review]
Thanks again for taking the time to submit this and sorry the review took some time :(

I know this isn't true for the existing samples but I tend to think simpler samples are better and so most of the changes I've made are in deleting redundant portions of the sample.

In addition to that, I also:

- updated the description of the lexer; and
- added aliases for the filename extensions.

Let me know what you think!

**Comment by ljcooke** [comment]
@pyrmont No worries about the delay. These changes look good to me! :)

**Review by pyrmont — APPROVED** [review]

**Comment by pyrmont** [comment]
@ljcooke This will be part of the next release of Rouge, v3.23.0. That's actually scheduled for release later today/early tomorrow (depending on your time zone) so will be available from RubyGems pretty soon 🎉 Thanks for improving Rouge!

**Pull request merged**
